#ifndef __ESPRITEID_H__
#define __ESPRITEID_H__
enum eSpriteID
{
	// All ID Enemy Sprite
	SPRITE_MENUBG = 0,
	SPRITE_MAP_1 = 1,
	SPRITE_MAP_2 = 2,
	SPRITE_MAP_3 = 3,
	SPRITE_BIG_GUN_ROATING = 4, SPRITE_BIG_GUN_ROTAING_POPUP,
	SPRITE_BOSS_CENTER, SPRITE_GUN_BOSS, SPRITE_BOSS_BODY_DEAD, SPRITE_BOSS_BODY_ALIVE, SPRITE_BOSS_DIE, SPRITE_BOSS_EXPLOISION,

	SPRITE_BRIDGE_BODY, SPRITE_BRIDGE_HEAD, SPRITE_BRIDGE_TAIL, SPRITE_BRIDGE, SPRITE_HEAD_BREAK, SPRITE_TAIL_BREAK, SPRITE_BRIDGE_EXPLOISION,
	SPRITE_BULLET_BIG,
	SPRITE_F_BULLET,
	SPRITE_ENEMY_RUN,
	SPRITE_ENEMY_WITH_BIG_GUN,
	SPRITE_ENEMY_RUN_SHOOTING,
	SPRITE_CAPSULE_BOSS, SPRITE_BIG_CAPSULE_BOSS,
	SPRITE_EXPLOISION,
	SPRITE_WEAPON_CAPSULE,	SPRITE_WEAPON_SENSOR, 	
	SPRITE_FLAME_GUN, SPRITE_MACHINE_GUN, SPRITE_LASER_GUN, SPRITE_BARRIER,	SPRITE_SPREAD_GUN, SPRITE_RAPID_FIRE,
	SPRITE_GRID,
	SPRITE_GUN_ROTATING,
	SPRITE_ICON,
	

	SPRITE_RAMBO_CLIMB,
	SPRITE_RAMBO_BEFORE_DEAD,
	SPRITE_RAMBO_DIVE,
	SPRITE_RAMBO_IDLE,
	SPRITE_RAMBO_JUMP,
	SPRITE_RAMBO_LIE,
	SPRITE_RAMBO_MOVE_BODY,
	SPRITE_RAMBO_MOVE_LEG,
	SPRITE_RAMBO_RUN,
	SPRITE_RAMBO_SHOOT_BODY,
	SPRITE_RAMBO_SHOOT_BOTTOM_RIGHT,
	SPRITE_RAMBO_SHOOT_BOTTOM_RIGHT_BODY,
	SPRITE_RAMBO_SHOOT_RUN,
	SPRITE_RAMBO_SHOOT_TOP_RIGHT,
	SPRITE_RAMBO_SHOOT_TOP_RIGHT_BODY,
	SPRITE_RAMBO_SHOOT_UP,
	SPRITE_RAMBO_SHOOT_UP_BODY,
	SPRITE_RAMBO_SWIM,
	SPRITE_RAMBO_WATER_BOMB,

	SPRITE_SNIPER_HIDING,
	SPRITE_SNIPER_WATER_HIDING,
	SPRITE_SNIPER_HIDING_EXPLOISION,
	SPRITE_SNIPER_SHOOTING,
	SPRITE_SNIPER_STANDING_BOT,
	SPRITE_SNIPER_STANDING_MID,
	SPRITE_SNIPER_STANDING_TOP,
	SPRITE_SHOOTING,

	SPRITE_ROCK_FALLING,
	SPRITE_MAGIC_ROCK,

	SPRITE_DEFAULT_BULLET_RAMBO,
	SPRITE_FIRE_BULLET_RAMBO,
	SPRITE_LED_OBJECT,
	SPRITE_MEDAL,
	SPRITE_EFFECT_MAP1,
	SPRITE_EFFECT_MAP2,
	SPRITE_LAZE_BULLET_RAMBO,
	COUNT_SPRITE,
	SPRITE_FIRE,
	SPRITE_TANK,
	SPRITE_FIRE_BRIDGE,
	// End all ID Enemy Sprite
};
#endif