#ifndef __eObjectID_h__
#define __eObjectID_h__
enum eObjectID
{
	TILE_BASE,
	VIRTUAL_OBJECT_WATER,
	RAMBO,
	BULLET_RAMBO,
	BULLET_ENEMY,
	SNIPER_STANDING,
	SNIPER_HIDING,
	GIF_BULLET_STATIC,
	GIF_BULLET_MOVING,
	GUN_ROTATING,
	BIG_GUN_ROTATING,
	ENEMY_RUN,
	BOSS_GUN,
	BOSS_CENTER,
	BIG_BOSS_1, // Boss Map 1
	BULLET, //  Cai nay de lam gi???
	LED_OBJECT_STAR,
};
#endif