#ifndef __eObjectID_h__
#define __eObjectID_h__
enum eObjectID
{
	TILE_BASE,
	VIRTUAL_OBJECT_WATER,
	RAMBO,
	BULLET_RAMBO,
	BULLET_ENEMY,
	SNIPER_STANDING,
	SNIPER_HIDING,
	WEAPON_SENSOR,	WEAPON_CAPSULE,
	OBJECT_BARRIER, OBJECT_FLAME_GUN, OBJECT_LASER_GUN, OBJECT_MACHINE_GUN, OBJECT_RAPID_GUN, OBJECT_SPREAD_GUN,
	GUN_ROTATING,
	BIG_GUN_ROTATING,
	ENEMY_RUN,
	BOSS_GUN,	BOSS_CENTER, BIG_BOSS_1, // Boss Map 1
	BULLET, //  Cai nay de lam gi???
	LED_OBJECT_STAR,
	TILE_BACKGROUND,
	BRIDGE_HEAD, BRIDGE_TAIL, BRIDGE_BODY, BRIDGE,
	VIRTUAL_OBJECT_JUMP,
	BULLET_BOSS1,
	MAGIC_ROCK,
	SNIPPER_WATER_HIDING,
	STONE,
	FIRE,
	//BULLET_SNIPPER_WATER_HIDING,
};
#endif